#!/bin/bash
echo "📦 Flutter Pub Get..."
~/development/flutter/bin/flutter pub get

echo "🚀 Building Web Project (HTML Renderer)..."
~/development/flutter/bin/flutter build web --web-renderer html --release

echo "📂 Syncing Assets..."
cp -r assets/data build/web/assets/

echo "✅ Build Complete!"