name: orthodoxy_widget_365
description: "A new Flutter project for Nikos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  share_plus: ^7.2.2
  url_launcher: ^6.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
  fonts:
    - family: GFSDidot
      fonts:
        - asset: assets/fonts/GFSDidot-Regular.ttf